### ISSUE TITLE
Getting bug on dismiss without scroll

### ISSUE THREAD

**Issue by Faiyyaz** [figengungor/country_pickers#36]
```
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following NoSuchMethodError was thrown while resolving an image:
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      double.> (dart:core-patch/double.dart:96:31)
#2      max (dart:math-patch/math_patch.dart:45:9)
#3      _clipOffsetToScrollableRange (package:flutter/src/widgets/list_wheel_scroll_view.dart:362:19)
#4      _getItemFromOffset (package:flutter/src/widgets/list_wheel_scroll_view.dart:354:11)
...
Image provider: ScrollAwareImageProvider<dynamic>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#fe6d4(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, size: Size(30.0, 20.0), platform: iOS)
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#fe6d4(), name: "packages/country_pickers/assets/af.png", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════════════════════════
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════════════════════════
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
════════════════════════════════════════════════════════════════════════════════════════════════════
Application finished.

```

**Comment by AbdOoSaed** [comment]
@Faiyyaz 

I fix this issue in my fork
I used this workaround 
https://github.com/flutter/flutter/issues/61228#issuecomment-749826206

 country_pickers:
    git:
      url: https://github.com/AbdOoSaed/country_pickers.git
